# vim:filetype=sh

# Set X preferences
# Disable bell
xset -b
# disable screen saver
xset -dpms
xset s off

# Monitor setup
autorandr --change

# Move cursor to center of screen
xdotool mousemove --polar 0 0

# Hide cursor
unclutter & disown

# Keyboard bindings
[[ -f "$HOME/.Xmodmap" ]] && xmodmap "$HOME/.Xmodmap"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec i3
