#!/bin/env sh

# Set X preferences
# Disable bell
xset -b
# disable screen saver
xset -dpms
xset s off

eval $(ssh-agent)

# Monitor setup
autorandr --change

# Keyboard bindings
[[ -f "$HOME/.Xmodmap" ]] && xmodmap "$HOME/.Xmodmap"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec i3
