#!/bin/sh

# Set X preferences
# Disable bell
xset -b
# disable screen saver
xset -dpms
xset s off

# Monitor setup
autorandr --change

# Move cursor to center of screen
xdotool mousemove --polar 0 0

# Hotkeys
sxhkd &

# Hide cursor
unclutter &
# shellcheck disable=SC3044
disown

# Set capslock to Ctrl when pressed; Esc when held
setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape' -t 200

# Keyboard bindings
[ -f "$HOME/.Xmodmap" ] && xmodmap "$HOME/.Xmodmap"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		# shellcheck disable=SC1090
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

exec i3
