# Use nwg-piotr for GUI management
[[profile]]
name = "default"
exec = []
[[profile.output]]
match = "eDP-1"
enable = true
mode = { width = 1920, height = 1080, refresh = 60 }
position = { x = 1920, y = 0 }
[[profile.output]]
match = "DVI-I-1"
enable = true
mode = { width = 1920, height = 1080, refresh = 60 }
position = { x = 3840, y = 0 }
[[profile.output]]
match = "DVI-I-2"
enable = true
mode = { width = 1920, height = 1080, refresh = 60 }
position = { x = 0, y = 0 }
