#!/usr/bin/env bash
#
# A zathura script to open a link in another window
# It opens another zathura instance if one doesn't exist already then move it to the right monitor
#
# Dependencies: zathura xdotool ydotool wtype i3/sway

# How it works:
# Given: Zathura is able to store a link's page number in the clipboard
# Steps:
# - Store current clipboard
# - copy link's page number to clipboard
# - if Zathura has another instance opening the same file
#   - goto page in opened instance
#   - else, open page in a new instance. Move it to righ output
# - Place back clipboard

main() {
	local -r file="$1"

	local page
	page="$(get_page_num)" || exit 1
	readonly page

	open_document "$file" "$page"
}

#######################################
# Pick a link and get number of page in zathura
#######################################
get_page_num() {
	clipboard_copy ""

	ydotool key 46:1 46:0

	# Wait until the page number is copied  or the action is aborted
	wait_keys "<esc>" "<ctrl>+m" >/dev/null

	page="$(clipboard_paste)"

	[[ ! $page =~ ^[0-9]+$ ]] && echo 'Page needs to be an integer' >&2 && exit 1

	# For some reason, zathura gives page-1
	page=$((page + 1))

	# Clear zathura's message
	if [[ -n "${WAYLAND_DISPLAY}" ]]; then
		wtype -P escape -p escape
	elif [[ -n "${DISPLAY}" ]]; then
		xdotool key --clearmodifiers Escape
	fi

	echo "$page"
}

#######################################
# Go to a page in an openned or new instance of zathura then move to right output
# Arguments:
#   1: file path
#   2: page number
#######################################
open_document() {
	local -r file="$1"
	local -r page="$2"

	if [[ -n "${WAYLAND_DISPLAY}" ]]; then
		focused_pid="$(swaymsg -t get_tree | jq '.. | select(.focused?) | .pid')"
	elif [[ -n "${DISPLAY}" ]]; then
		focused_pid="$(xdotool getactivewindow getwindowpid)"
	fi

	# Quote brackets "( )", because xdotool has special meaning for them
	file_quoted="${file//(/\\(}"
	file_quoted="${file_quoted//)/\\)}"
	# All pids using the file
	if [[ -n "${WAYLAND_DISPLAY}" ]]; then
		# Get PIDs
		all_pids="$(swaymsg -t get_tree | jq -r ".. | select(.name? == \"${file_quoted}\") | .pid")"
	elif [[ -n "${DISPLAY}" ]]; then
		all_pids="$(xdotool search --name "^${file_quoted}$" getwindowpid %@)"
	fi

	other_pid="$(grep -v "$focused_pid" <(echo "$all_pids"))"
	if [[ -n "$other_pid" ]]; then
		busctl --user call "org.pwmt.zathura.PID-$other_pid" /org/pwmt/zathura org.pwmt.zathura GotoPage u "$((page - 1))"
	else
		zathura --page="$page" "$file" &
		if [[ -n "${WAYLAND_DISPLAY}" ]]; then
			while ! swaymsg -t get_tree | jq -r ".. | select(.name? == \"${file_quoted}\")? | .pid" | grep -v "$focused_pid"; do
				sleep 0.1
			done
			other_pid="$(swaymsg -t get_tree | jq -r ".. | select(.name? == \"${file_quoted}\")? | .pid" | grep -v "$focused_pid")"
			swaymsg -t get_tree | jq -r --arg pid "$other_pid" '.. | select(.pid? == ($pid | tonumber))? | .id' | while read -r container_id; do
				swaymsg "[con_id=$container_id] move output right" 2>/dev/null
			done
		elif [[ -n "${DISPLAY}" ]]; then
			# Wait until the PID for the new instance is available
			while ! xdotool search --name "^${file_quoted}$" getwindowpid %@ | grep -v "$focused_pid"; do
				sleep 0.1
			done
			other_pid="$(xdotool search --name "^${file_quoted}$" getwindowpid %@ | grep -v "$focused_pid")"
			window_ids="$(xdotool search --pid "$other_pid")"
			for id in $window_ids; do
				i3-msg "[id=$id] move output right" 2>/dev/null
			done
		fi
	fi
	if [[ -n "${WAYLAND_DISPLAY}" ]]; then
		swaymsg "[pid=$other_pid app_id=\"org.pwmt.zathura\"] focus"
	elif [[ -n "${DISPLAY}" ]]; then
		xdotool search --onlyvisible --all --pid "$other_pid" --class 'zathura' windowfocus
	fi
}

# Preserve clipboard during script
old_clipboard="$(clipboard_paste)"
main "$@"
trap 'clipboard_copy $old_clipboard' EXIT
