#!/usr/bin/env bash

# Open a document to a page or using its name
# Dependencies: fd

books_path="$HOME/books"
file_path="$1"
page_num="$2"

encode_url() {
  # Reliable localization
  local LC_ALL=C
  # Go through each character
  for (( i = 0; i < ${#1}; i++ )); do
    : "${1:i:1}"
    case "$_" in
      # Keep allowed characters
      [a-zA-Z0-9.~_-]) printf '%s' "$_" ;;
      # Encode disallowed characters
      *) printf '%%%02X' "'$_" ;;
    esac
  done
  printf '\n'
}

doc_basename="${file_path##*/}"
doc_name="${doc_basename%.*}"
link_name="$doc_name"

cmd='zathura "$(fd --fixed-strings --search-path '${books_path}' "'${doc_name}'")"'
if [[ $page_num ]]; then
    cmd+=" --page=$page_num"
    link_name+=", page $page_num"
fi
cmd+=" & disown"

encoded_command="$(encode_url "$cmd")"

org_url="[[link-handler://${encoded_command}][${link_name}]]"

echo "$org_url" | xclip -selection clipboard
