#!/usr/bin/env sh

file_path="$1"
page_num="$2"

encode_url() {
  # Reliable localization
  local LC_ALL=C
  # Go through each character
  for (( i = 0; i < ${#1}; i++ )); do
    : "${1:i:1}"
    case "$_" in
      # Keep allowed characters
      [a-zA-Z0-9.~_-]) printf '%s' "$_" ;;
      # Encode disallowed characters
      *) printf '%%%02X' "'$_" ;;
    esac
  done
  printf '\n'
}

document_basename="$(basename "$file_path")"
document_name="${document_basename%.*}"

encoded_command="$(encode_url "$(echo "zathura \"${file_path}\" --page=$page_num & disown")")"
org_url="[[link-handler://${encoded_command}][$document_name, page $page_num]]"

echo $org_url | xclip -selection clipboard
