#!/usr/bin/env bash
# alias | awk -F'[ =]' '{print $2}'
# declare -f | awk -F'[ ()]' '{print $1}' | grep -E '^[[:alpha:]]'
# Faster than the above method
cat <<EOF
calc
org
_org
_emacs
syncorg
pick_color
gitdotfiles
rcreadline
rcdotfiles
rcgpg
rcgit
rcsway
rcwaybar
rcssh
rcx11
rcbash
rczsh
rckitty
rcvim
rci3
rcneomutt
rcmutt
rctuir
rcnewsboat
rcfeh
rcrofi
rcdunst
rcpolybar
rctmux
rczathura
rcqutebrowser
rcemacs
testmail
EOF
