#!/bin/env sh

# TODO: If session is open in a terminal -> focus that terminal
get_available_sesions()
{
    tmux list-sessions | cut -d: -f1
}

if [ -z $@ ]
then
    echo ;get_available_sesions
else
    SESSION=$@

    if [ "${SESSION}" = "empty" ]
    then
        fzftm >/dev/null
    elif [ -n "${SESSION}" ]; then
        alacritty -e tmux attach-session -t "${SESSION}" > /dev/null & disown
    fi
fi
