#!/bin/env sh

# Dependencies: fasd (for frecency), fd (searching files), rofi (interface)
# Get documents or delete them using <C-d>
# TODO: Keep rofi open after file deletion.
# Can be done by making another script that runs rofi more than one time
# Maybe an unimplemented feature: Check https://github.com/davatorium/rofi/issues/1595
# TODO: use -dmenu argument to show the <C-d> binding

get_documents() {

    docs_path=$(fd --regex '.*.(pdf|djvu|epub)$')
    docs_basename=$(echo "$docs_path" | sed -e 's/\(.*\)/"\1"/' | xargs basename --multiple)
    # for frecency (tracks only the visited files)
    fasd_docs=$(fasd -lR "$docs_basename" | sed -e 's/\(.*\)/"\1"/' | xargs basename --multiple)
    # get all files
    all_docs="$fasd_docs\n$docs_basename"
    no_duplicates=$(echo "$all_docs" | awk '!a[$0]++')
    echo "$no_duplicates"
}

if [ -z $@ ]; then

# Enable ability to use custom keys <C-d> used to delete files
echo -en "\0use-hot-keys\x1ftrue\n"
echo ; get_documents
else
    DOCUMENT=$@

    if [ "${DOCUMENT}" = "empty" ]
    then
        dunstify "Empty"
    elif [ -n "${DOCUMENT}" ]
    then
        DOCUMENT_PATH=$HOME/$(fd -F "${DOCUMENT}" | head -n 1)
        if [[ $ROFI_RETV -eq 10 ]]; then
            rm "$DOCUMENT_PATH"
        else
            # append path to fasd for frecency (frequency and recency)
            fasd -A "$DOCUMENT_PATH"
            zathura "$DOCUMENT_PATH" >/dev/null & disown
        fi
    fi
fi
