#!/bin/env sh

# Get number of new e-mails

if [[ -d $HOME/.local/share/mail/ ]]; then
  out=$(find $HOME/.local/share/mail/*/INBOX/new/ -type f|wc -l)

  if [ "$out" != "0" ]; then
    echo $out
  else
    echo ""
  fi
else
  echo ""
fi
