#!/usr/bin/env bash
# https://github.com/polybar/polybar/issues/763
flock 200

killall -q polybar

while pgrep -u $UID -x polybar > /dev/null; do sleep 0.5; done

outputs=$(xrandr --query | grep " connected" | cut -d" " -f1)
primary_output=$(xrandr --query | grep " primary" | cut -d" " -f1)

# execute polybar for each screen and assign tray for the main window
for m in $outputs; do
    export MONITOR=$m
    export TRAY_POSITION=none

    if [[ $m == "$primary_output" ]]; then
        polybar --reload middle_bar </dev/null > "/var/tmp/polybar-$m.log" 2>&1 200>&- &
    else
        polybar --reload generic_bar </dev/null > "/var/tmp/polybar-$m.log" 2>&1 200>&- &
    fi
    disown
done
