#!/usr/bin/env bash
#
# Include window focus after doing dunst action

source "$HOME/.bashrc.d/functions.bash"

# Needed for i3-msg in Sway to work
if [[ -n "${WAYLAND_DISPLAY}" ]]; then
  I3SOCK="/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock"
  export I3SOCK
fi

[[ $(dunstify "$2" "$3" --appname slack-delegate --action="action,label") == "action" ]] && {
  ! is_window_exists '^Slack$' && slack
  dunstify hello
  goto_window '^Slack$'
}
