#!/usr/bin/env bash
#
# Include thunderbird function in functions.bash

source "$HOME/.bashrc.d/functions.bash"
# Needed for i3-msg in Sway to work
if [[ -n "${WAYLAND_DISPLAY}" ]]; then
	I3SOCK="/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock"
	export I3SOCK
fi

[[ $(dunstify "$2" "$3" --appname Thunderbird-delegate --action="action,label") == "action" ]] && {
	thunderbird
}
