#!/usr/bin/env bash
#
# Include thunderbird function in functions.bash

source "$HOME/.bashrc.d/functions.bash"

# Needed for i3-msg in Sway to work
if [[ -n "${WAYLAND_DISPLAY}" ]]; then
	I3SOCK="/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock"
	export I3SOCK
fi

[[ $(dunstify "$2" "$3" --appname Thunderbird-delegate --action="action,label") == "action" ]] && {
	thunderbird
} &

# If notifcations are paused, don't dim screens
[[ "$(dunstctl is-paused)" == "true" ]] && exit 0

# Reduce brigness if idle
SECONDS_WAIT=3
declare SRC_FILE
SRC_FILE="$(mktemp)"

dim() {
	# Fetch valid bus numbers
	buses=$(ddcutil detect | awk '/^Display/ {p=1} /^Invalid/ {p=0} p && /\/dev\/i2c-/ {print $NF}' | sed 's/.*i2c-//')

	# Dim Laptop
	brightnessctl set 5% &

	# Dim monitors by looping through each valid bus number to dim them immediately
	for bus in $buses; do
		ddcutil --bus "$bus" --noverify --sleep-multiplier .5 setvcp 10 0 &
	done
}

undim() {
	# 1. Fetch valid bus numbers
	buses=$(ddcutil detect | awk '/^Display/ {p=1} /^Invalid/ {p=0} p && /\/dev\/i2c-/ {print $NF}' | sed 's/.*i2c-//')

	brightnessctl set 80% &

	for bus in $buses; do
		ddcutil --bus "$bus" --noverify --sleep-multiplier .5 setvcp 10 80 &
	done

	pkill swayidle
}

declare -f dim undim >>"$SRC_FILE"

pid=$$
# If idle, dim then undim after activity
# Also kill this process before it kills swayidle
swayidle -w timeout "$SECONDS_WAIT" "source $SRC_FILE; kill $pid; dim; " resume "source $SRC_FILE; undim; rm $SRC_FILE" &

# If not-idle, kill swayidle process
# Rationale: After doing an action, swayidle will refresh the timeout which
# will then allow for the killing of the process beforehand.
SWAYIDLE_PID=$!

sleep $((SECONDS_WAIT + 1))

kill $SWAYIDLE_PID 2>/dev/null
rm "$SRC_FILE"
pkill -P $$
