#!/usr/bin/env bash

declare -r CONFIG_FILE="$XDG_CONFIG_HOME/dunst/dunstrc"
OUTPUT=$(mktemp)
declare -r OUTPUT
trap 'rm -f $OUTPUT' EXIT

source "$HOME/bin/helpers/monitor_variables" >/dev/null
sed "
s/follow[[:space:]]*=[[:space:]]*[a-z]\+/follow = none/
s/monitor[[:space:]]*=[[:space:]]*[a-zA-Z1-9\-]\+/monitor = $MONITOR_MIDDLE/
" "$CONFIG_FILE" >"$OUTPUT"

dunstctl reload "$OUTPUT"
