/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-01-GoldbergVariationsBwv.988-Aria.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-02-GoldbergVariationsBwv.988-Variation1.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-03-GoldbergVariationsBwv.988-Variation2.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-04-GoldbergVariationsBwv.988-Variation3.CanonOnTheUnison.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-05-GoldbergVariationsBwv.988-Variation4.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-06-GoldbergVariationsBwv.988-Variation5.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-07-GoldbergVariationsBwv.988-Variation6.CanonOnTheSecond.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-08-GoldbergVariationsBwv.988-Variation7.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-09-GoldbergVariationsBwv.988-Variation8.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-10-GoldbergVariationsBwv.988-Variation9.CanonOnTheThird.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-11-GoldbergVariationsBwv.988-Variation10.Fughetta.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-12-GoldbergVariationsBwv.988-Variation11.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-13-GoldbergVariationsBwv.988-Variation12.CanonOnTheFourth.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-14-GoldbergVariationsBwv.988-Variation13.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-15-GoldbergVariationsBwv.988-Variation14.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-16-GoldbergVariationsBwv.988-Variation15.CanonOnTheFifth.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-17-GoldbergVariationsBwv.988-Variation16.Overture.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-18-GoldbergVariationsBwv.988-Variation17.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-19-GoldbergVariationsBwv.988-Variation18.CanonOnTheSixth.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-20-GoldbergVariationsBwv.988-Variation19.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-21-GoldbergVariationsBwv.988-Variation20.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-22-GoldbergVariationsBwv.988-Variation21.CanonOnTheSeventh.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-23-GoldbergVariationsBwv.988-Variation22.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-24-GoldbergVariationsBwv.988-Variation23.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-25-GoldbergVariationsBwv.988-Variation24.CanonOnTheOctave.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-26-GoldbergVariationsBwv.988-Variation25.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-27-GoldbergVariationsBwv.988-Variation26.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-28-GoldbergVariationsBwv.988-Variation27.CanonOnTheNinth.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-29-GoldbergVariationsBwv.988-Variation28.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-30-GoldbergVariationsBwv.988-Variation29.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-31-GoldbergVariationsBwv.988-Variation30.Quodlibet.flac
/home/yasser/Music/Musicc/ClassicalMusic/Bach_GoldbergVariations/JohannSebastianBach-32-GoldbergVariationsBwv.988-AriaDaCapo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Beethoven_CoriolanOverture/LudwigVanBeethoven-CoriolanOverture.flac
/home/yasser/Music/Musicc/ClassicalMusic/Beethoven_EgmontOvertureOp.84/LudwigVanBeethoven-EgmontOvertureOp.84.flac
/home/yasser/Music/Musicc/ClassicalMusic/Beethoven_StringQuartetNo.6inBFlatMajorOp.18/LudwigVanBeethoven-StringQuartetNo.6InBFlatMajorOp.18No.6-01-AllegroConBrio.flac
/home/yasser/Music/Musicc/ClassicalMusic/Beethoven_StringQuartetNo.6inBFlatMajorOp.18/LudwigVanBeethoven-StringQuartetNo.6InBFlatMajorOp.18No.6-02-AdagioMaNonTroppo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Beethoven_StringQuartetNo.6inBFlatMajorOp.18/LudwigVanBeethoven-StringQuartetNo.6InBFlatMajorOp.18No.6-03-ScherzoAllegro.flac
/home/yasser/Music/Musicc/ClassicalMusic/Beethoven_StringQuartetNo.6inBFlatMajorOp.18/LudwigVanBeethoven-StringQuartetNo.6InBFlatMajorOp.18No.6-04-adagioLaMalinconia.flac
/home/yasser/Music/Musicc/ClassicalMusic/Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-01-AllegroConBrio.flac
/home/yasser/Music/Musicc/ClassicalMusic/Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-02-MarciaFunebreAdagioAssai.flac
/home/yasser/Music/Musicc/ClassicalMusic/Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-03-ScherzoAllegroVivace.flac
/home/yasser/Music/Musicc/ClassicalMusic/Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-04-FinaleAllegroMolto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Borodin_InTheSteppesOfCentralAsia/AlexanderBorodin-InTheSteppesOfCentralAsia.flac
/home/yasser/Music/Musicc/ClassicalMusic/Borodin_StringQuartetNo.1inAMajor/AlexanderBorodin-StringQuartetNo.1InAMajor-01-Moderato-Allegro.flac
/home/yasser/Music/Musicc/ClassicalMusic/Borodin_StringQuartetNo.1inAMajor/AlexanderBorodin-StringQuartetNo.1InAMajor-02-AndanteConMoto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Borodin_StringQuartetNo.1inAMajor/AlexanderBorodin-StringQuartetNo.1InAMajor-03-ScherzoPrestissimo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Borodin_StringQuartetNo.1inAMajor/AlexanderBorodin-StringQuartetNo.1InAMajor-04-Andante-AllegroRisoluto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Borodin_StringQuartetNo.2inDMajor/AlexanderBorodin-StringQuartetNo.2InDMajor-01-AllegroModerato.flac
/home/yasser/Music/Musicc/ClassicalMusic/Borodin_StringQuartetNo.2inDMajor/AlexanderBorodin-StringQuartetNo.2InDMajor-02-ScherzoAllegro.flac
/home/yasser/Music/Musicc/ClassicalMusic/Borodin_StringQuartetNo.2inDMajor/AlexanderBorodin-StringQuartetNo.2InDMajor-03-NocturneAndante.flac
/home/yasser/Music/Musicc/ClassicalMusic/Borodin_StringQuartetNo.2inDMajor/AlexanderBorodin-StringQuartetNo.2InDMajor-04-FinaleAndante-Vivace.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.1inCMinor/JohannesBrahms-SymphonyNo.1InCMinorOp.68-01-UnPocoSostenuto-Allegro.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.1inCMinor/JohannesBrahms-SymphonyNo.1InCMinorOp.68-02-AndanteSostenuto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.1inCMinor/JohannesBrahms-SymphonyNo.1InCMinorOp.68-03-UnPocoAllegrettoEGrazioso.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.1inCMinor/JohannesBrahms-SymphonyNo.1InCMinorOp.68-04-Adagio-PiAndante-AllegroNonTroppoMaConBrio.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.2inDMajor/JohannesBrahms-SymphonyNo.2InDMajorOp.73-01-AllegroNonTroppo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.2inDMajor/JohannesBrahms-SymphonyNo.2InDMajorOp.73-02-AdagioNonToppo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.2inDMajor/JohannesBrahms-SymphonyNo.2InDMajorOp.73-03-AllegrettoGraziosotake1.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.2inDMajor/JohannesBrahms-SymphonyNo.2InDMajorOp.73-03-AllegrettoGraziosotake2.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.2inDMajor/JohannesBrahms-SymphonyNo.2InDMajorOp.73-04-AllegroConSpirito.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.3inFMajor/JohannesBrahms-SymphonyNo.3InFMajorOp.90-01-AllegroConBrio.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.3inFMajor/JohannesBrahms-SymphonyNo.3InFMajorOp.90-02-Andante.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.3inFMajor/JohannesBrahms-SymphonyNo.3InFMajorOp.90-03-PocoAllegretto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.3inFMajor/JohannesBrahms-SymphonyNo.3InFMajorOp.90-04-Allegro.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.4inEMinor/JohannesBrahms-SymphonyNo.4InEMinorOp.98-01-AllegroNonTroppo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.4inEMinor/JohannesBrahms-SymphonyNo.4InEMinorOp.98-02-AndanteModerato.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.4inEMinor/JohannesBrahms-SymphonyNo.4InEMinorOp.98-03-AllegroGiocoso.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_SymphonyNo.4inEMinor/JohannesBrahms-SymphonyNo.4InEMinorOp.98-04-AllegroEnergicoEPassionato.flac
/home/yasser/Music/Musicc/ClassicalMusic/Brahms_TragicOverture/JohannesBrahms-TragicOverture.flac
/home/yasser/Music/Musicc/ClassicalMusic/Dvorak_StringQuartetNo.10inEFlatOp.51/AntonnDvorak-StringQuartetNo.10InEFlatOp.51-01-AllegroMaNonTroppo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Dvorak_StringQuartetNo.10inEFlatOp.51/AntonnDvorak-StringQuartetNo.10InEFlatOp.51-02-Dumka.flac
/home/yasser/Music/Musicc/ClassicalMusic/Dvorak_StringQuartetNo.10inEFlatOp.51/AntonnDvorak-StringQuartetNo.10InEFlatOp.51-03-Romanza.flac
/home/yasser/Music/Musicc/ClassicalMusic/Dvorak_StringQuartetNo.10inEFlatOp.51/AntonnDvorak-StringQuartetNo.10InEFlatOp.51-04-FinaleAllegroAssai.flac
/home/yasser/Music/Musicc/ClassicalMusic/Dvorak_StringQuartetNo.12inFMajorOp.96/AntonnDvorak-StringQuartetNo.12InFMajorOp.96American-01-AllegroMaNonTroppo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Dvorak_StringQuartetNo.12inFMajorOp.96/AntonnDvorak-StringQuartetNo.12InFMajorOp.96American-02-Lento.flac
/home/yasser/Music/Musicc/ClassicalMusic/Dvorak_StringQuartetNo.12inFMajorOp.96/AntonnDvorak-StringQuartetNo.12InFMajorOp.96American-03-MoltoVivace.flac
/home/yasser/Music/Musicc/ClassicalMusic/Dvorak_StringQuartetNo.12inFMajorOp.96/AntonnDvorak-StringQuartetNo.12InFMajorOp.96American-04-Finale-VivaceMaNonTroppo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-01-Morning.flac
/home/yasser/Music/Musicc/ClassicalMusic/Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-02-AasesDeath.flac
/home/yasser/Music/Musicc/ClassicalMusic/Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-03-AnitrasDream.flac
/home/yasser/Music/Musicc/ClassicalMusic/Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-04-InTheHallOfTheMountainKing.flac
/home/yasser/Music/Musicc/ClassicalMusic/Haydn_StringQuartetInDMajorOp.64/JosephHaydn-StringQuartetInDOp.645H363Lark-01-AllegroModerato.flac
/home/yasser/Music/Musicc/ClassicalMusic/Haydn_StringQuartetInDMajorOp.64/JosephHaydn-StringQuartetInDOp.645H363Lark-02-AdagioCantabile.flac
/home/yasser/Music/Musicc/ClassicalMusic/Haydn_StringQuartetInDMajorOp.64/JosephHaydn-StringQuartetInDOp.645H363Lark-03-MenuettoAllegretto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Haydn_StringQuartetInDMajorOp.64/JosephHaydn-StringQuartetInDOp.645H363Lark-04-FinaleVivace.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_Hebrides/FelixMendelssohn-HebridesOvertureFingalsCave.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_ItalianSymphony/FelixMendelssohn-SymphonyNo.4InAMajorOp.90italian-01-AllegroVivace.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_ItalianSymphony/FelixMendelssohn-SymphonyNo.4InAMajorOp.90italian-02-AndanteConMoto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_ItalianSymphony/FelixMendelssohn-SymphonyNo.4InAMajorOp.90italian-03-ConMotoModerato.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_ItalianSymphony/FelixMendelssohn-SymphonyNo.4InAMajorOp.90italian-04-Saltarellopresto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_ScottishSymphony/FelixMendelssohn-SymphonyNo.3InAMinorscottishOp.56-01-AndanteConMoto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_ScottishSymphony/FelixMendelssohn-SymphonyNo.3InAMinorscottishOp.56-02-VivaceNonTroppo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_ScottishSymphony/FelixMendelssohn-SymphonyNo.3InAMinorscottishOp.56-03-Adagio.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_ScottishSymphony/FelixMendelssohn-SymphonyNo.3InAMinorscottishOp.56-04-AllegroVivacissimo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_StringQuartetNo.6inFMinorOp.80/FelixMendelssohn-StringQuartetNo.6InFMinorOp.80-01-AllegroVivaceAssai.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_StringQuartetNo.6inFMinorOp.80/FelixMendelssohn-StringQuartetNo.6InFMinorOp.80-02-AllegroAssai.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_StringQuartetNo.6inFMinorOp.80/FelixMendelssohn-StringQuartetNo.6InFMinorOp.80-03-Adagio.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mendelssohn_StringQuartetNo.6inFMinorOp.80/FelixMendelssohn-StringQuartetNo.6InFMinorOp.80-04-Fuga.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_MagicFluteOverture/WolfgangAmadeusMozart-MagicFluteOverture.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_MarriageOfFigaro/WolfgangAmadeusMozart-MarriageOfFigaro.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_StringQuartetNo.15inDMinorK421/WolfgangAmadeusMozart-StringQuartetNo.15InDMinorK421-01-AllegroModerato.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_StringQuartetNo.15inDMinorK421/WolfgangAmadeusMozart-StringQuartetNo.15InDMinorK421-02-Andante.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_StringQuartetNo.15inDMinorK421/WolfgangAmadeusMozart-StringQuartetNo.15InDMinorK421-03-Minuetto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_StringQuartetNo.15inDMinorK421/WolfgangAmadeusMozart-StringQuartetNo.15InDMinorK421-04-AllegroMaNonTroppo.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_StringQuartetNo.19inCMajorK465/WolfgangAmadeusMozart-StringQuartetNo.19InCK465Dissonance-01-AdagioAllegro.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_StringQuartetNo.19inCMajorK465/WolfgangAmadeusMozart-StringQuartetNo.19InCK465Dissonance-02-AndanteCantabile.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_StringQuartetNo.19inCMajorK465/WolfgangAmadeusMozart-StringQuartetNo.19InCK465Dissonance-03-MinuettoAllegretto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_StringQuartetNo.19inCMajorK465/WolfgangAmadeusMozart-StringQuartetNo.19InCK465Dissonance-04-AllegroVolto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-01-MoltoAllegro.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-02-Andante.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-03-MenuettoAllegretto.flac
/home/yasser/Music/Musicc/ClassicalMusic/Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-04-AllegroAssai.flac
/home/yasser/Music/Musicc/ClassicalMusic/Rimsky-Korsakov_RussianOverture/NikolaiRimsky-korsakov-RussianEasterFestivalOvertureOp.36.flac
/home/yasser/Music/Musicc/ClassicalMusic/Schubert_SonataInAMajorD.664/FranzSchubert-SonataInAMajorD.664-01-AllegroModerato.flac
/home/yasser/Music/Musicc/ClassicalMusic/Schubert_SonataInAMajorD.664/FranzSchubert-SonataInAMajorD.664-02-Andante.flac
/home/yasser/Music/Musicc/ClassicalMusic/Schubert_SonataInAMajorD.664/FranzSchubert-SonataInAMajorD.664-03-Allegro.flac
