#!/usr/bin/env bash

monitor_primary=""
monitor_left=""
monitor_right=""

# Get the primary monitor
monitor_primary=$(xrandr --query | grep primary | awk '{print $1}')

# Iterate over the monitor list and determine their relative positions
while read -r _ name details; do
    # Extract the position
    position=$(echo "$details" | grep -oP '\+\d+\+\d+')

    # Clean up the monitor name (removing '+' & '*' if present)
    clean_name=$(echo "$name" | tr -d '+' | tr -d '*')

    # Determine relative position
    if [ "$name" == "$monitor_primary" ]; then
        monitor_primary="$clean_name"
    elif [[ $position < "+1920+0" ]]; then
        monitor_left="$clean_name"
    else
        monitor_right="$clean_name"
    fi
done < <(xrandr --listmonitors | tail -n +2)

output="
workspace \$browser output $monitor_primary
workspace \$coding output $monitor_primary
workspace \$notes output $monitor_primary
workspace \$video output $monitor_primary
workspace \$documents output $monitor_primary

workspace \$git output $monitor_right

workspace \$wp6 output $monitor_left
workspace \$wp9 output $monitor_left
workspace \$social output $monitor_left
"
echo -e "$output" >| "$XDG_CONFIG_HOME/i3/monitor_setup"
