#!/usr/bin/env bash

output="
workspace \$browser output $MONITOR_PRIMARY
workspace \$coding output $MONITOR_PRIMARY
workspace \$notes output $MONITOR_PRIMARY
workspace \$video output $MONITOR_PRIMARY
workspace \$documents output $MONITOR_PRIMARY

workspace \$git output $MONITOR_RIGHT

workspace \$wp6 output $MONITOR_LEFT
workspace \$wp9 output $MONITOR_LEFT
workspace \$social output $MONITOR_LEFT
"
echo -e "$output" >| "$XDG_CONFIG_HOME/i3/monitor_setup"
