#!/usr/bin/env bash
# Move specific windows to scratchpad or kill them
#
# dependencies: i3/sway jq

SCRATCHPAD_WINDOWS=(
	"Zotero"
	"org.mozilla.Thunderbird"
)

for window in "${SCRATCHPAD_WINDOWS[@]}"; do
	is_match="$(i3-msg -t get_tree | jq --arg re "$window" '
      any(
        recurse(.nodes[]?, .floating_nodes[]?);
        .focused and (
          ((.name // "") | test($re)) or
          ((.app_id // "") | test($re)) or
          ((.window_properties.class // "") | test($re))
        )
      )
    ')"

	if [[ "$is_match" == "true" ]]; then
		i3-msg "$(window_get_condition "$window")" move scratchpad
		exit 0
	fi
done

i3-msg kill
