#!/usr/bin/env bash
# Move specific windows to scratchpad or kill them
#
# dependencies: i3/sway jq

SCRATCHPAD_WINDOWS=(
    "Zotero"
    "org.mozilla.Thunderbird"
)

for window in "${SCRATCHPAD_WINDOWS[@]}"; do

    focused_window_id="$(i3-msg -t get_tree | jq --arg re "$window" '
    .. | objects
    | select(
    .focused and (
        (.name? == $re) or
        (.app_id? == $re) or
        (.window_properties.class? == $re))
    ) | .id
    ')"

    # Window focus isn't in the list
    [[ -z "$focused_window_id" ]] && continue

    # Get all window ids that have same property
    windows_ids="$(i3-msg -t get_tree | jq --arg re "$window" '
    .. | objects
    | select(
        (.name? == $re) or
        (.app_id? == $re) or
        (.window_properties.class? == $re)
    ) | .id
    ')"

    # If the window id is not the smallest -> it's a secondary window
    if [[ "$(echo "$windows_ids" | wc -l)" -gt 1 ]]; then
        [[ "$("$windows_ids" | head -n 1)" != "$focused_window_id" ]] && break
    fi

    # NOTE: Sway needs fullscreen disabled; otherwise, it bugs out when other windows are fullscreened
    i3-msg "[con_id=$focused_window_id] fullscreen disable" && i3-msg "[con_id=$focused_window_id] move scratchpad"
    exit 0
done

i3-msg kill
