#!/usr/bin/env bash
# Close window or hide it if it's Zotero
#
# Dependencies: i3 jq

# Returns true or false
Zotero_main_window="$(i3-msg -t get_tree | jq -r ' recurse(.nodes[]?, .floating_nodes[]?)
| select(.focused)
| .window_properties.class == "Zotero" and  .window_properties.instance == "Navigator"')"

if [[ "$Zotero_main_window" == "true" ]]; then
	i3-msg '[class="Zotero"] move scratchpad '
else
	i3-msg 'kill'
fi
