#!/bin/env bash

# Dependencies: i3 sway
# Set the configuration focus_on_window_activation that enables or disables
# focus of activated windows
# Available options smart smart|urgent|focus|none
# https://i3wm.org/docs/userguide.html#focus_on_window_activation

options=("smart" "urgent" "focus" "none")
declare -r tmp_file_path=/tmp/i3_focus_config

# Sleep for $1 seconds and revert back to normal behaviour
revert_changes_after_delay() {
	sleep "$1"
	"$0" "smart"
}

if [[ ! ${options[*]} =~ $1 ]]; then
	notify-send "$1 is an invalid option"
	exit 0
fi

# Extend the sleep time until it reverts back by storing the PID of the command
# and check its existence on a later execution
if [[ $2 == [[:digit:]] ]]; then
	curr_pid="$(cat "$tmp_file_path" 2>/dev/null)"
	{ kill -0 "$curr_pid" && kill "$curr_pid"; } 2>/dev/null
	revert_changes_after_delay "$2" &
	curr_pid=$!
	echo $curr_pid >$tmp_file_path
fi

if [ -n "${WAYLAND_DISPLAY}" ]; then
	swaymsg "focus_on_window_activation $1"
	wait
	swaymsg "focus_on_window_activation smart"
else
	sed -i "1s/.*/focus_on_window_activation $1/" "$XDG_CONFIG_HOME/i3/focus_on_window_activation_config"
	i3-msg reload
	wait
	i3-msg reload
fi
