#!/usr/bin/env bash

# Generate a bitwarden item that contains login info

TITLE="$QUTE_TITLE"
URL="$QUTE_URL"
BASE_URL="$(echo "$URL" | cut -d / -f -3)"

# Temporary fix for the "bw generate" hanging
{ sleep 5 && pkill -f "bw generate"; } &
PASSWORD="$(bw generate -lusn --length 18)"

TMP_FILE=$(mktemp)
TEMPLATE=$(bw get template item | jq ".name=\"$TITLE\" | .notes=\"\" | .login=$(bw get template item.login | jq '.username="yasser.kaddoura19@gmail.com" | .password="'"${PASSWORD}"'" | .uris=[{"match":null,"uri":"'"${BASE_URL}"'"}]')")
CLASS="bitwarden_editor"
echo "$TEMPLATE" >|"$TMP_FILE"

"$TERMINAL" --class "$CLASS" -e "$EDITOR" "$TMP_FILE" +":call cursor (10,12)"

echo "$PASSWORD" | xclip -selection c
echo "message-info 'Password yanked'" >>"$QUTE_FIFO"

ENCODED_JSON="$(bw encode <"$TMP_FILE")"

bw create item "$ENCODED_JSON"

rm "$TMP_FILE"
