#!/usr/bin/env bash
# shellcheck disable=SC2206

# Download paper from scihub and open it

DOWNLOAD_PATH="${HOME}/Downloads"

shopt -s nullglob
# To know if the file got downloaded, check if number of files increased
FILES=(${DOWNLOAD_PATH}/*)
NUM_FILES=${#FILES[@]}
scihub --overwrite Y --search "$QUTE_URL" --outdir "${DOWNLOAD_PATH}" 
FILES_CURR=(${DOWNLOAD_PATH}/*)
NUM_FILES_CURR=${#FILES_CURR[@]}

[[ $NUM_FILES_CURR -eq $NUM_FILES ]] && echo "message-info 'failed to install paper'" >> "$QUTE_FIFO" && exit 0

# Open latest document modified
xdg-open "$(find "${DOWNLOAD_PATH}" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d' ')" & disown
i3-msg 'workspace --no-auto-back-and-forth 8'
