#!/bin/env sh

url_root="$(echo $QUTE_URL | awk -F '/' '{print $3}')"

qute_command="open --$1"

[[ "$url_root" != "github.com" ]] && echo "$qute_command $url_root" >> "$QUTE_FIFO"  && exit

git_root="$(echo $QUTE_URL | cut -d / -f -5)"

echo "$qute_command $git_root" >> "$QUTE_FIFO"
