#!/bin/env sh

auth=$(bw get item bitly | jq -r '.fields[] | select(.name == "password") | .value')
# use https://api-ssl.bitly.com/v4/groups to get group-uid
group=$(bw get item bitly | jq -r '.fields[] | select(.name == "key") | .value')

function bitly_request {
    curl \
        -H "Authorization: Bearer $auth" \
        -H 'Content-Type: application/json' \
        -X POST \
        -d "{
            \"long_url\": \"$QUTE_URL\",
            \"group_guid\": \"$group\"
        }" https://api-ssl.bitly.com/v4/shorten
}

response=$(bitly_request $1) 2>/dev/null


shortened_link=$(echo $response | jq '.link' | sed 's/"//g')
echo $shortened_link | xclip -selection clipboard
echo "message-info 'url shortened'" >> "$QUTE_FIFO"
