#!/usr/bin/env bash
#
# Shorten URLs and yank them into clipboard
#
# Dependencies: Bitly credentials, jq

auth=$(pass bitly/key)
# use https://api-ssl.bitly.com/v4/groups to get group-uid
group=$(pass bitly/group_guid)

function bitly_request  {
    curl \
        -H "Authorization: Bearer $auth" \
        -H 'Content-Type: application/json' \
        -X POST \
        -d "{
            \"long_url\": \"$QUTE_URL\",
            \"group_guid\": \"$group\"
        }" https://api-ssl.bitly.com/v4/shorten
}

response=$(bitly_request "$1") 2>/dev/null


shortened_link=$(echo "$response" | jq '.link' | sed 's/"//g')
clipboard_copy "$shortened_link"
echo "message-info 'url shortened'" >> "$QUTE_FIFO"
