#!/usr/bin/env bash

# Download and open document it instead of opening the tab in special cases
# Dependencies: curl, pup, zathura, dunstify

if [[ "$QUTE_URL" == "" ]]; then
    exit
fi

url_root_special_case="libgen.rocks"
# url_root_special_case="library.lol"
count=60

alias urldecode='python -c "import sys, urllib.parse as ul; \
    print(ul.unquote_plus(sys.argv[1]))"'

alias urlencode='python -c "import sys, urllib.parse as ul; \
    print(ul.quote_plus(sys.argv[1]))"'

get_file_size() {
    ls -ls "$document_path" | awk -F ' ' '{print $1}'
}

url_root="$(echo $QUTE_URL | awk -F '/' '{print $3}')"

#  Open file normally if the url is not a special case
[[ $url_root != $url_root_special_case ]] && echo "open $QUTE_URL"  >> $QUTE_FIFO && exit

# Otherwise download the document
download_url=$(curl -s $QUTE_URL | pup 'a[href*="get"]' attr{href})

url_download=$(echo "https://$url_root_special_case/$download_url" | sed 's/amp;//')

echo "open $url_download" >> $QUTE_FIFO
