#!/usr/bin/env bash

# Download and open document it instead of opening the tab in special cases
# Dependencies: curl, pup, zathura, dunstify

if [[ "$QUTE_URL" == "" ]]; then
	exit
fi

alias urldecode='python -c "import sys, urllib.parse as ul; \
    print(ul.unquote_plus(sys.argv[1]))"'

alias urlencode='python -c "import sys, urllib.parse as ul; \
    print(ul.quote_plus(sys.argv[1]))"'

MIRROR_LINK=$(echo "$QUTE_SELECTED_HTML" | pup 'a[href]' "attr{href}")
DOWNLOAD_LINK="${MIRROR_LINK%/*}/$(curl -s "$MIRROR_LINK" | pup 'a[href*="get"]' 'attr{href}')"

DOWNLOAD_LINK="${DOWNLOAD_LINK/amp;/}"

echo "open $DOWNLOAD_LINK" >>"$QUTE_FIFO"
