#!/usr/bin/env bash
#
# Script used by Qutebrowser's to select files
# 
# $1 path to place file paths
# $2 command type (directory, file, files)

FILE_PATH="$1"

case "$2" in
  "directory") pick_file --frecency --type directory | xargs -I {} realpath {} > "$FILE_PATH" ;;
  "file") pick_file --frecency --type file | xargs -I {} realpath {} > "$FILE_PATH" ;;
  "files") pick_file --frecency --multi --type file | xargs -I {} realpath {} > "$FILE_PATH" ;;
  *) echo "Only directory, file, & files are valid" ;;
esac

