#!/bin/env sh

~/.config/i3/set_i3_focus_on_window_activation_configuration none
emacsclient --no-wait "org-protocol://capture?url=$QUTE_URL&title=$QUTE_TITLE"
sleep 0.5
~/.config/i3/set_i3_focus_on_window_activation_configuration smart

echo ":message-info 'Note captured'" >> $QUTE_FIFO
