#!/usr/bin/env bash

tmp_dir_file="/tmp/ranger_dir"
prev_date_file="/tmp/ranger_date"

curr_date="$(date +%s)"
if [[ -f $prev_date_file ]]; then
  prev_date="$(cat $prev_date_file)"
  date_diff=$((curr_date-prev_date))
  # Remove default directory after 30 minutes from last use
  [[ $((date_diff/60)) -ge 1 ]] && rm $tmp_dir_file
fi
echo "$curr_date" >| "$prev_date_file"

dir="$(cat "$tmp_dir_file" 2>/dev/null || echo '')"
ranger --choosefiles="$1" --choosedir="$tmp_dir_file" "$dir"
