#!/usr/bin/env bash

# Yank org link
# options:
# --clean: If it's a github repo root, get the package name only

title="$QUTE_TITLE"
url="$QUTE_URL"

# Assign it to the github repo name only
if [[ "$1" == "--clean" ]]; then
    url_root="$(echo $QUTE_URL | awk -F '/' '{print $3}')"

    # Should be at root of the repo
    # Checked by counting number of dashes
    num_dashes=$(echo "$QUTE_URL" | grep -o "/" | wc -l)

    if [[ "$url_root" == "github.com" && $num_dashes == 4 ]]; then
        title=$(echo "$QUTE_TITLE" | awk -F : '{ print $1}')
    fi
    url="${url%#*}"
fi

echo -n "[[$url][$title]]" | xclip -selection c
echo "message-info 'url turned to org url'" >> "$QUTE_FIFO"
