#!/usr/bin/env bash

LIB_LINK="https://libgen.li/index.php"
QUERY="$(grep "(Author)" <(cat "$QUTE_TEXT") | sed s/"(Author)"//g | tr ' ' +)"
# Remove format line
QUERY="${QUERY%Format*}"
cp "$QUTE_HTML" ~/bla.html

TITLE="$(pup --file "$QUTE_HTML" "#productTitle text{}")"
LINK="$LIB_LINK?req=${TITLE:2}+${QUERY:2:-1}&order=year&ordermode=desc&covers=on"

echo "open -w $LINK" >> "$QUTE_FIFO"
