#!/usr/bin/env python
# coding=utf-8
# Description: yanks URLs of open tabs as org URLs

import os
import subprocess
import time

import yaml

SESSION_FILE_NAME = "userscript_session"
SESSION_PATH = f"{os.environ['HOME']}/.local/share/qutebrowser/sessions"


def get_markdown_urls():
    file_path = f"{SESSION_PATH}/{SESSION_FILE_NAME}.yml"
    urls = {}

    with open(file_path, "r") as stream:
        try:
            windows = yaml.safe_load(stream)["windows"]
            for window in windows:
                # get the last url in the history of each tab (aka current url)
                for tab in window["tabs"]:
                    current_url = tab["history"][-1]
                    urls[current_url["title"]] = current_url["url"]
        except yaml.YAMLError:
            pass

    org_urls = [f"- [[{title}][{url}]]" for (url, title) in urls.items()]

    parsed_urls = "\n" + "\n".join(org_urls)

    return parsed_urls


def main():
    subprocess.Popen(
        (
            f"echo 'session-save {SESSION_FILE_NAME} --only-active-window --quiet' >> {os.environ['QUTE_FIFO']}"
        ),
        shell=True,
        text=True,
    )
    time.sleep(0.1)
    # extract urls for buffers
    markdown_urls = get_markdown_urls()
    command = f'clipboard_copy "{markdown_urls}"'
    os.system(command)
    subprocess.Popen(
        (f"echo 'message-info \"yanked urls\"' >> {os.environ['QUTE_FIFO']}"),
        shell=True,
        text=True,
    )


if __name__ == "__main__":
    main()
