#!/usr/bin/env bash

# Yank org link
# dependencies:
# remove_emoji script
# options:
# --clean: If it's a github repo root, get the package name only

TITLE="$QUTE_TITLE"
URL="$QUTE_URL"

# Assign it to the github repo name only
if [[ "$1" == "--clean" ]]; then
	URL_ROOT="$(echo "$URL" | awk -F '/' '{print $3}')"

	# Should be at root of the repo
	# Checked by counting number of dashes
	NUM_DASHES=$(echo "$URL" | grep -o "/" | wc -l)

	if [[ "$URL_ROOT" == "github.com" && $((NUM_DASHES)) -ge 4 ]]; then
		# shellcheck disable=2026
		URL="$(echo "$URL" | cut -d / -f -5)"
		TITLE="$(echo "$URL" | cut -d / -f 4-)"
	fi
fi

# Emojis are removed because org link-prettier shows the link twice for titles
# containing emojis
TITLE_NO_EMOJI="$("$HOME/bin/remove_emoji" "$TITLE")"

copy_to_clipboard "[[$URL][$TITLE_NO_EMOJI]]"

echo "message-info 'url turned to org url'" >>"$QUTE_FIFO"
