#!/usr/bin/env bash

lib_link="https://libgen.li/index.php"
link="$lib_link?req=$QUTE_SELECTED_TEXT&order=year&ordermode=desc"
echo "$link" | xclip -selection clipboard
echo "message-info 'URL copied to clipboard'" >> "$QUTE_FIFO"
