#!/usr/bin/env bash
#
# Use video transcription service on youtube video

URL_ROOT="$(echo "$QUTE_URL" | awk -F '/' '{print $3}')"

[[ "$URL_ROOT" != "www.youtube.com" ]] \
  && echo "message-info 'Not youtube video'" >> "$QUTE_FIFO" \
  && exit 0

ID="$(echo "$QUTE_URL" | tr "?&#" "\n" | grep "^v=" | cut -d "=" -f 2)"

echo "open -t https://www.youtube-transcript.io/videos/$ID" >>"$QUTE_FIFO"
